"""add datetime and update tags

Revision ID: 77c2bc2b6614
Revises: a9bbdd4a740d
Create Date: 2025-10-04 12:17:04.602020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c2bc2b6614'
down_revision: Union[str, Sequence[str], None] = 'a9bbdd4a740d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tags', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.create_foreign_key(None, 'tags', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('tags', 'category_id')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
